version: "3"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: tinyurldb


#version: "3"
#services:
#  fastapi:
#    build: .  # Specify the path to the Dockerfile
#    ports:
#      - "8000:8000"
#    depends_on:
#      - postgres
#  postgrbes:
#    image: postgres:latest
#    environment:
#      - POSTGRES_USER=docker
#      - POSTGRES_PASSWORD=docker
#      - POSTGRES_DB=tinyurldb
